version: "3.9"
services:
    sqlserver:
      build:
        context: .
        dockerfile: ./SqlServer/Dockerfile
      ports:
        - "1436:1433"

    projectapi:
      build:
        context: ./ProjectAPI
        dockerfile: ./Dockerfile
      ports:
        - "8088:80"
      depends_on:
        - sqlserver
      environment:
        - ASPNETCORE_ENVIRONMENT=Docker